// <auto-generated />
using System;
using Contract_Report2.ModelDataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contract_Report2.ModelDataLayer.Migrations
{
    [DbContext(typeof(Contract_ReportDBContext))]
    [Migration("20240813022807_1403-05-22-01")]
    partial class _1403052201
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contract_Report2.ModelDataLayer.Entities.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("EconomyCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsWin")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompanyID");

                    b.HasIndex("ContractId");

                    b.ToTable("tbCompany");
                });

            modelBuilder.Entity("Contract_Report2.ModelDataLayer.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("BankGurantee")
                        .HasColumnType("bit");

                    b.Property<string>("BudgetApprovalDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudgetRequestDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Committee")
                        .HasColumnType("bit");

                    b.Property<bool>("CommitteeApproval")
                        .HasColumnType("bit");

                    b.Property<string>("ContractDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndWorkDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EstimatedCost")
                        .HasColumnType("real");

                    b.Property<float?>("FixedAmount")
                        .HasColumnType("real");

                    b.Property<string>("HowToAssign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RateDeadline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealFinishDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewAndEditting")
                        .HasColumnType("bit");

                    b.Property<string>("StratWorkDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeExtension")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbContract");
                });

            modelBuilder.Entity("Contract_Report2.ModelDataLayer.Entities.Contract_Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("tbContract-Status");
                });

            modelBuilder.Entity("Contract_Report2.ModelDataLayer.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("tbSattus");
                });

            modelBuilder.Entity("Contract_Report2.ModelDataLayer.Entities.Company", b =>
                {
                    b.HasOne("Contract_Report2.ModelDataLayer.Entities.Contract", "contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.Navigation("contract");
                });

            modelBuilder.Entity("Contract_Report2.ModelDataLayer.Entities.Contract_Status", b =>
                {
                    b.HasOne("Contract_Report2.ModelDataLayer.Entities.Status", "status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("status");
                });
#pragma warning restore 612, 618
        }
    }
}
